### ISSUE TITLE
Script doesn't work after updating to OSX Yosemite

### ISSUE THREAD

**Issue by khemikooligan** [TigerDX/HomePasser#1]
I really like this script, much more so than the relaymyhome script running around, sadly after my computer crashed I was forced to reinstall OSX. I was previously running Mavericks, however my new hard drive has been updated to Yosemite and unfortunately now after inputting "sudo python homepasser.py" I get the lines:

Password:
Initializing wireless interface
/System/Library/LaunchDaemons/com.apple.InternetSharing.plist: No such file or directory
Cycling WiFi...
/System/Library/LaunchDaemons/com.apple.InternetSharing.plist: No such file or directory
HomePassing on en1 with 4E:53:50:4F:4F:06 for 60 seconds

The "no such file or directory" error is given before each cycling and I fail to receive any streetpasses

**Comment by benmurden** [comment]
Thanks for the report.

It seems the InternetSharing.plist changed in the new version of OSX, so hopefully it'll be a simple matter of changing the reference and everything else working as it should. However, I too did not upgrade to Yosemite, so I would have no way of testing such changes.

I will see about making sensible changes on another branch, then I may ask for help testing it.

**Comment by benmurden** [comment]
I have pushed some changes to the Yosemite branch, with OSX version detection, so if you get a chance, could you test it for me? Thanks again.

**Comment by benmurden** [comment]
Haven't heard anything, so closing this issue for now.
